# Causal Analysis

[1] Zheng, X., Aragam, B., Ravikumar, P., & Xing, E. P. (2018). [DAGs with NO TEARS: Continuous optimization for structure learning](https://arxiv.org/abs/1803.01422) ([NeurIPS 2018](https://nips.cc/Conferences/2018/), Spotlight).

[2] Zheng, X., Dan, C., Aragam, B., Ravikumar, P., & Xing, E. P. (2020). [Learning 
sparse nonparametric DAGs](https://arxiv.org/abs/1909.13189) ([AISTATS 2020](https://aistats.org/), to appear).

In [1]:
! pip3 install causalnex pandas numpy

Collecting causalnex
  Downloading causalnex-0.10.0-py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 19.0 MB/s eta 0:00:01
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (1.1.5)
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (1.19.5)
Requirement already satisfied: scipy<1.6,>=1.2.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from causalnex) (1.5.3)
Requirement already satisfied: networkx~=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from causalnex) (2.5)
Collecting wrapt<1.12,>=1.11.0
  Downloading wrapt-1.11.2.tar.gz (27 kB)
Collecting torch~=1.7
  Downloading torch-1.9.0-cp36-cp36m-manylinux1_x86_64.whl (831.4 MB)
     |████████████████████████████▌   | 739.8 MB 83.3 MB/s eta 0:00:02     |██████▍                         | 167.4 MB 83.5 MB/s eta 0:00:08��██▏     | 681.1 MB 84.6 MB/s eta 0:00:02

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

     |████████████████████████████████| 831.4 MB 7.2 kB/s
Collecting scikit-learn!=0.22.2.post1,!=0.24.1,<0.25.0,>=0.22.0
  Downloading scikit_learn-0.24.2-cp36-cp36m-manylinux2010_x86_64.whl (22.2 MB)
     |████████████████████████████████| 22.2 MB 44.5 MB/s eta 0:00:01
Requirement already satisfied: pathos<0.3.0,>=0.2.7 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from causalnex) (0.2.7)
Collecting pgmpy<0.2.0,>=0.1.12
  Downloading pgmpy-0.1.14-py3-none-any.whl (331 kB)
     |████████████████████████████████| 331 kB 51.0 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.7.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas) (2021.1)
Requirement already satisfied: decorator>=4.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from networkx~=2.5->causalnex) (4.4.2)
Requirement already satisfied: pox>=0.2.9 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pathos<0.3.0,>=0.2.7->causalnex) (0.2.9)
Requirement already satisfied: dill>=0.3.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pathos<0.3.0,>=0.2.7->causalnex) (0.3.3)
Requirement already satisfied: multiprocess>=0.70.11 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pathos<0.3.0,>=0.2.7->causalnex) (0.70.11.1)
Requirement already satisfied: ppft>=1.6.6.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pathos<0.3.0,>=0.2.7->causalnex) (1.6.6.3)
Requirement already satisfied: pyparsing in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pgmpy<0.2.0,>=0.1.12->causalnex) (2.4.7)
Requirement already satisfied: statsmodels in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pgmpy<0.2.0,>=0.1.12->causalnex) (0.12.2)
Requirement already satisfied: joblib in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pgmpy<0.2.0,>=0.1.12->causalnex) (1.0.1)
Collecting tqdm
  Downloading tqdm-4.61.1-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 6.5 MB/s  eta 0:00:01
Requirement already satisfied: six>=1.7.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from ppft>=1.6.6.3->pathos<0.3.0,>=0.2.7->causalnex) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scikit-learn!=0.22.2.post1,!=0.24.1,<0.25.0,>=0.22.0->causalnex) (2.1.0)
Requirement already satisfied: typing-extensions in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from torch~=1.7->causalnex) (3.7.4.3)
Requirement already satisfied: dataclasses in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from torch~=1.7->causalnex) (0.8)
Requirement already satisfied: patsy>=0.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from statsmodels->pgmpy<0.2.0,>=0.1.12->causalnex) (0.5.1)
Building wheels for collected packages: wrapt
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.11.2-cp36-cp36m-linux_x86_64.whl size=66708 sha256=92535720216d30a42615f5e2e1b4e610f5ecba68abc8b9997d214b7dce150e35
  Stored in directory: /home/ec2-user/.cache/pip/wheels/0d/85/48/15d7bfab92a2d0e87372224c1f628fc57db7447a663a58e86c
Successfully built wrapt
Installing collected packages: tqdm, torch, scikit-learn, wrapt, pgmpy, causalnex
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.1
    Uninstalling scikit-learn-0.24.1:
      Successfully uninstalled scikit-learn-0.24.1
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.12.1
    Uninstalling wrapt-1.12.1:
      Successfully uninstalled wrapt-1.12.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 1.2.1 requires botocore<1.19.53,>=1.19.52, but you have botocore 1.20.76 which is incompatible.
Successfully installed causalnex-0.10.0 pgmpy-0.1.14 scikit-learn-0.24.2 torch-1.9.0 tqdm-4.61.1 wrapt-1.11.2

In [2]:
# silence warnings
import warnings
import pandas as pd
import numpy as np
from causalnex.structure.notears import from_pandas
from causalnex.structure import StructureModel
from IPython.display import Image
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE


warnings.filterwarnings("ignore")
sm = StructureModel()

In [3]:
df_train = pd.read_csv("data/cina/cina0_train.data", header=None, sep=" ")
df_train.drop(columns=132, inplace=True)
df_train.head(5)

,0,1,2,3,4,5,6,7,8,9,...,122,123,124,125,126,127,128,129,130,131
0,1,0,0,0,1,0,0,0,0,0,...,0,562,562,1,0,1,562,1,0,0
1,0,0,0,0,1,0,0,0,1,0,...,0,562,812,1,0,0,749,0,0,0
2,0,1,0,0,1,0,0,0,1,0,...,0,624,624,1,0,0,562,0,0,0
3,0,0,0,0,1,1,0,0,1,0,...,1,624,812,0,0,1,624,0,0,0
4,1,0,0,0,1,0,0,0,0,0,...,0,562,562,1,0,0,874,0,0,0

In [4]:
df_target = pd.read_csv("data/cina/cina0_train.targets", header=None, sep=" ")
df_target.head(5)

   0
0  1
1 -1
2 -1
3 -1
4 -1

In [5]:
df_train[132] = df_target[0]
df_train.head(5)

,0,1,2,3,4,5,6,7,8,9,...,123,124,125,126,127,128,129,130,131,132
0,1,0,0,0,1,0,0,0,0,0,...,562,562,1,0,1,562,1,0,0,1
1,0,0,0,0,1,0,0,0,1,0,...,562,812,1,0,0,749,0,0,0,-1
2,0,1,0,0,1,0,0,0,1,0,...,624,624,1,0,0,562,0,0,0,-1
3,0,0,0,0,1,1,0,0,1,0,...,624,812,0,0,1,624,0,0,0,-1
4,1,0,0,0,1,0,0,0,0,0,...,562,562,1,0,0,874,0,0,0,-1

In [ ]:
sm = from_pandas(df_train)

In [ ]:
viz = plot_structure(
    sm,
    graph_attributes={"scale": "0.5"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK)
Image(viz.draw(format='png'))